param(
    [Parameter(Mandatory)][string]$GitHubOwner,
    [Parameter(Mandatory)][string]$GitHubRepo,
    [string]$GitHubToken = $env:GITHUB_TOKEN
)

$GH_API_BASE = "https://api.github.com"

$labels = @(
    @{ name="hot";            color="B60205"; description="AttentionScore 80+ / Critical CVE" }
    @{ name="high";           color="D93F0B"; description="AttentionScore 50-79" }
    @{ name="medium";         color="E4E669"; description="AttentionScore 25-49" }
    @{ name="low";            color="C2E0C6"; description="AttentionScore 0-24" }
    @{ name="llm";            color="7057FF"; description="OWASP LLM Top10 related" }
    @{ name="agent";          color="5319E7"; description="OWASP Agentic AI Top10 related" }
    @{ name="ml";             color="0052CC"; description="OWASP ML Security Top10 related" }
    @{ name="ai-security";    color="006B75"; description="AI/ML security general" }
    @{ name="cve";            color="1D76DB"; description="Has CVE identifier" }
    @{ name="cisa-kev";       color="E11D48"; description="CISA KEV listed - exploited in the wild" }
    @{ name="auto-generated"; color="BFD4F2"; description="Auto-generated by AI CVE Analyzer" }
)

function Invoke-GitHubLabelApi {
    param([string]$Method, [string]$Endpoint, [string]$Body = "")
    $url = "$GH_API_BASE$Endpoint"
    $wc  = New-Object System.Net.WebClient
    $wc.Encoding = [System.Text.Encoding]::UTF8
    $wc.Headers.Add("Authorization", "token $GitHubToken")
    $wc.Headers.Add("Accept",        "application/vnd.github.v3+json")
    $wc.Headers.Add("Content-Type",  "application/json; charset=utf-8")
    $wc.Headers.Add("User-Agent",    "AI-CVE-Analyzer/1.0")
    try {
        if ($Method -eq "GET") { return $wc.DownloadString($url) | ConvertFrom-Json }
        else { return $wc.UploadString($url, $Method, $Body) | ConvertFrom-Json }
    } catch {
        return $null
    }
}

Write-Host ""
Write-Host "=== GitHub Label Setup ===" -ForegroundColor Cyan
Write-Host "  Repo: $GitHubOwner/$GitHubRepo"
Write-Host ""

$existing = Invoke-GitHubLabelApi -Method "GET" `
    -Endpoint "/repos/$GitHubOwner/$GitHubRepo/labels?per_page=100"
$existingNames = if ($existing) { $existing | ForEach-Object { $_.name } } else { @() }

foreach ($lbl in $labels) {
    if ($existingNames -contains $lbl.name) {
        Write-Host "  SKIP (exists): $($lbl.name)" -ForegroundColor DarkGray
        continue
    }

    $payload = @{
        name        = $lbl.name
        color       = $lbl.color
        description = $lbl.description
    } | ConvertTo-Json -Compress

    $resp = Invoke-GitHubLabelApi -Method "POST" `
        -Endpoint "/repos/$GitHubOwner/$GitHubRepo/labels" `
        -Body $payload

    if ($resp -and $resp.name) {
        Write-Host "  OK: $($lbl.name)" -ForegroundColor Green
    } else {
        Write-Host "  FAIL: $($lbl.name)" -ForegroundColor Red
    }
    Start-Sleep -Milliseconds 500
}

Write-Host ""
Write-Host "=== Done ===" -ForegroundColor Cyan
Write-Host "Next: Run Step4_Create-GitHubIssues.ps1 -DryRun to verify"
Write-Host ""
