param(
    [string]$InputPath    = ".\work\cve_analyzed.json",
    [Parameter(Mandatory)]
    [string]$GitHubOwner,
    [Parameter(Mandatory)]
    [string]$GitHubRepo,
    [string]$GitHubToken  = $env:GITHUB_TOKEN,
    [int]   $MinScore     = 50,
    [switch]$DryRun,
    [int]   $MaxIssues    = 20
)

$ErrorActionPreference = "Stop"

$GH_API_BASE  = "https://api.github.com"
$NVD_BASE_URL = "https://nvd.nist.gov/vuln/detail"

function Invoke-GitHubApi {
    param([string]$Method, [string]$Endpoint, [string]$Body = "")
    $url = $GH_API_BASE + $Endpoint
    $wc  = New-Object System.Net.WebClient
    $wc.Encoding = [System.Text.Encoding]::UTF8
    $wc.Headers.Add("Authorization", "token $GitHubToken")
    $wc.Headers.Add("Accept",        "application/vnd.github.v3+json")
    $wc.Headers.Add("Content-Type",  "application/json; charset=utf-8")
    $wc.Headers.Add("User-Agent",    "AI-CVE-Analyzer/1.0")
    try {
        if ($Method -eq "GET") {
            return $wc.DownloadString($url) | ConvertFrom-Json
        } else {
            return $wc.UploadString($url, $Method, $Body) | ConvertFrom-Json
        }
    } catch [System.Net.WebException] {
        $code = [int]$_.Exception.Response.StatusCode
        Write-Warning "GitHub API error [$code]: $Endpoint"
        return $null
    }
}

function Get-ExistingIssueTitles {
    Write-Host "  Checking existing issues..." -ForegroundColor Cyan
    $titles = @{}
    $page   = 1
    do {
        $ep   = "/repos/$GitHubOwner/$GitHubRepo/issues?state=all" `
              + "&labels=cve" `
              + "&per_page=100" `
              + "&page=$page"
        $resp = Invoke-GitHubApi -Method "GET" -Endpoint $ep
        if (-not $resp -or $resp.Count -eq 0) { break }
        foreach ($issue in $resp) { $titles[$issue.title] = $true }
        $page++
    } while ($resp.Count -eq 100)
    return $titles
}

function Get-AttentionLabel {
    param([int]$Score)
    if ($Score -ge 80) { return "hot" }
    if ($Score -ge 50) { return "high" }
    if ($Score -ge 25) { return "medium" }
    return "low"
}

function Get-FrameworkLabels {
    param([string]$Framework)
    switch ($Framework.ToUpper()) {
        "LLM"      { return @("llm") }
        "AGENT"    { return @("agent") }
        "ML"       { return @("ml") }
        "MULTIPLE" { return @("llm", "agent", "ml") }
        default    { return @("ai-security") }
    }
}

function Build-OwaspTable {
    param($Cve)
    $llm = if ($Cve.OwaspLlm   -and $Cve.OwaspLlm.Count   -gt 0) { $Cve.OwaspLlm   -join ", " } else { "N/A" }
    $ag  = if ($Cve.OwaspAgent -and $Cve.OwaspAgent.Count -gt 0) { $Cve.OwaspAgent -join ", " } else { "N/A" }
    $ml  = if ($Cve.OwaspMl    -and $Cve.OwaspMl.Count    -gt 0) { $Cve.OwaspMl    -join ", " } else { "N/A" }

    $t  = "| Framework | Categories |`n"
    $t += "|---|---|`n"
    $t += "| OWASP LLM Top10 2025    | $llm |`n"
    $t += "| OWASP Agentic AI Top10  | $ag  |`n"
    $t += "| OWASP ML Security Top10 | $ml  |"
    return $t
}

function Build-IssueBody {
    param($Cve)

    $nvdUrl     = $NVD_BASE_URL + "/" + $Cve.CveId
    $epssVal    = if ($Cve.EpssScore)      { $Cve.EpssScore.ToString()      } else { "N/A" }
    $epssPerc   = if ($Cve.EpssPercentile) { $Cve.EpssPercentile.ToString() } else { "N/A" }
    $kevStr     = if ($Cve.InCisaKev)      { "YES - exploited in the wild"  } else { "No"  }
    $cvssStr    = if ($Cve.CvssScore)      { $Cve.CvssScore.ToString() + " / 10.0" } else { "N/A" }
    $pubStr     = if ($Cve.Published)      { $Cve.Published.ToString().Substring(0, 10) } else { "N/A" }
    $fwStr      = if ($Cve.PrimaryFramework) { $Cve.PrimaryFramework } else { "N/A" }
    $summaryStr = if ($Cve.SummaryJa)      { $Cve.SummaryJa      } else { "N/A" }
    $scenarioStr= if ($Cve.AttackScenario) { $Cve.AttackScenario  } else { "N/A" }

    # AvidIds is an array
    $avidStr = "N/A"
    if ($Cve.AvidIds -and $Cve.AvidIds.Count -gt 0) {
        $avidStr = ($Cve.AvidIds | ForEach-Object {
            "[" + $_ + "](https://avidml.org/database/" + $_ + ")"
        }) -join ", "
    }

    # Mitigation: array or string
    $mitigation = if ($Cve.Mitigation -is [array]) {
        ($Cve.Mitigation | ForEach-Object { "- " + $_ }) -join "`n"
    } elseif ($Cve.Mitigation) {
        $Cve.Mitigation
    } else { "N/A" }

    $owaspTable = Build-OwaspTable -Cve $Cve

    $body  = "<!-- Auto-generated by AI CVE Analyzer | " + (Get-Date -Format 'yyyy-MM-dd') + " -->`n`n"
    $body += "## Basic Info`n`n"
    $body += "| Item | Value |`n"
    $body += "|---|---|`n"
    $body += "| CVE ID | [$($Cve.CveId)]($nvdUrl) |`n"
    $body += "| AttentionScore | **$($Cve.AttentionScore) / 100** ($($Cve.AttentionLabel.ToUpper())) |`n"
    $body += "| CVSS | $cvssStr |`n"
    $body += "| EPSS | $epssVal (top $epssPerc%) |`n"
    $body += "| CISA KEV | $kevStr |`n"
    $body += "| AVID | $avidStr |`n"
    $body += "| Published | $pubStr |`n`n"
    $body += "---`n`n"
    $body += "## OWASP Mapping`n`n"
    $body += $owaspTable + "`n`n"
    $body += "**Primary Framework**: `` $fwStr ``  `n`n"
    $body += "---`n`n"
    $body += "## Risk Summary`n`n"
    $body += $summaryStr + "`n`n"
    $body += "---`n`n"
    $body += "## Attack Scenario`n`n"
    $body += $scenarioStr + "`n`n"
    $body += "---`n`n"
    $body += "## Mitigation`n`n"
    $body += $mitigation + "`n`n"
    $body += "---`n`n"
    $body += "## References`n`n"
    $body += "- NVD: $nvdUrl`n"
    if ($Cve.AvidIds -and $Cve.AvidIds.Count -gt 0) {
        foreach ($aid in $Cve.AvidIds) {
            $body += "- AVID: https://avidml.org/database/$aid`n"
        }
    }
    $body += "`n---`n"
    $body += "> Auto-generated by AI CVE Analyzer. Please review and approve before adding to SecAI Hub DB.`n"

    return $body
}

function Build-IssueTitle {
    param($Cve)
    $label = $Cve.AttentionLabel.ToUpper()
    $fw    = if ($Cve.PrimaryFramework) { " [" + $Cve.PrimaryFramework + "]" } else { "" }
    return "[$label] $($Cve.CveId)$fw"
}

# ============================================================
# Main
# ============================================================

Write-Host ""
Write-Host "============================================" -ForegroundColor Cyan
Write-Host " Step4: GitHub Issues Auto-Generator" -ForegroundColor Cyan
if ($DryRun) { Write-Host " [DRY RUN - No issues will be created]" -ForegroundColor Yellow }
Write-Host "============================================" -ForegroundColor Cyan
Write-Host ""

if (-not $GitHubToken) {
    Write-Error "GitHub Token not set. Use -GitHubToken or set env:GITHUB_TOKEN"
}
if (-not (Test-Path $InputPath)) {
    Write-Error "Input file not found: $InputPath"
}

# Use $PWD to avoid System32 path issue with [System.IO.File]
if ([System.IO.Path]::IsPathRooted($InputPath)) {
    $fullPath = $InputPath
} else {
    $fullPath = Join-Path $PWD $InputPath.TrimStart(".\")
}
Write-Host "Loading: $fullPath" -ForegroundColor Cyan
$jsonText = [System.IO.File]::ReadAllText($fullPath, [System.Text.Encoding]::UTF8)
$allCves  = $jsonText | ConvertFrom-Json
Write-Host "  Loaded $($allCves.Count) CVEs"

$targetCves = $allCves | Where-Object { $_.AttentionScore -ge $MinScore } |
              Sort-Object { [int]$_.AttentionScore } -Descending

Write-Host ""
Write-Host "Filter: AttentionScore >= $MinScore  =>  $($targetCves.Count) CVEs"

if ($targetCves.Count -gt $MaxIssues) {
    Write-Host "  Capped at $MaxIssues (use -MaxIssues to change)" -ForegroundColor Yellow
    $targetCves = $targetCves | Select-Object -First $MaxIssues
}
if ($targetCves.Count -eq 0) {
    Write-Host "  No CVEs to process. Exiting." -ForegroundColor Yellow
    exit 0
}

$hot  = ($targetCves | Where-Object { [int]$_.AttentionScore -ge 80 }).Count
$high = ($targetCves | Where-Object { [int]$_.AttentionScore -ge 50 -and [int]$_.AttentionScore -lt 80 }).Count
Write-Host "  HOT: $hot  /  HIGH: $high"
Write-Host ""

if (-not $DryRun) {
    $existingTitles = Get-ExistingIssueTitles
    Write-Host "  Existing issues found: $($existingTitles.Count)"
} else {
    $existingTitles = @{}
}
Write-Host ""

$created = 0; $skipped = 0; $errors = 0

foreach ($cve in $targetCves) {
    $title   = Build-IssueTitle -Cve $cve
    $attnLbl = Get-AttentionLabel  -Score ([int]$cve.AttentionScore)
    $fwLbls  = Get-FrameworkLabels -Framework $cve.PrimaryFramework
    $labels  = @("cve", $attnLbl, "auto-generated") + $fwLbls
    if ($cve.InCisaKev) { $labels += "cisa-kev" }

    $isDuplicate = $existingTitles.Keys | Where-Object { $_ -match [regex]::Escape($cve.CveId) }
    if ($isDuplicate) {
        Write-Host "  SKIP (duplicate): $($cve.CveId)" -ForegroundColor DarkGray
        $skipped++
        continue
    }

    if ($DryRun) {
        Write-Host "  [DRYRUN] $title" -ForegroundColor Yellow
        Write-Host "           Score : $($cve.AttentionScore) ($($attnLbl.ToUpper()))" -ForegroundColor Yellow
        Write-Host "           Labels: $($labels -join ', ')" -ForegroundColor Yellow
        Write-Host ""
        $created++
        continue
    }

    $body    = Build-IssueBody -Cve $cve
    $payload = @{
        title  = $title
        body   = $body
        labels = $labels
    } | ConvertTo-Json -Depth 5 -Compress

    $resp = Invoke-GitHubApi -Method "POST" `
        -Endpoint "/repos/$GitHubOwner/$GitHubRepo/issues" `
        -Body $payload

    if ($resp -and $resp.number) {
        Write-Host "  OK #$($resp.number): $($cve.CveId) [Score:$($cve.AttentionScore)]" -ForegroundColor Green
        $created++
    } else {
        Write-Host "  FAIL: $($cve.CveId)" -ForegroundColor Red
        $errors++
    }
    Start-Sleep -Seconds 1
}

Write-Host ""
Write-Host "============================================" -ForegroundColor Cyan
if ($DryRun) {
    Write-Host " Would create : $created issues [DRY RUN]" -ForegroundColor Yellow
} else {
    Write-Host " Created : $created" -ForegroundColor Green
    Write-Host " Skipped : $skipped (duplicates)" -ForegroundColor Gray
    Write-Host " Errors  : $errors" -ForegroundColor $(if ($errors -gt 0) { "Red" } else { "Gray" })
    if ($created -gt 0) {
        Write-Host ""
        Write-Host " https://github.com/$GitHubOwner/$GitHubRepo/issues" -ForegroundColor Cyan
    }
}
Write-Host "============================================" -ForegroundColor Cyan
Write-Host ""
