# src/stacksecai/pr_commenter.py
"""
PR Commenter: posts Policy Gate verdict as a GitHub PR comment.
"""
import os

import requests

VERDICT_BADGE = {
    "BLOCK": "🚫 BLOCK",
    "FLAG":  "⚠�E�EFLAG",
    "PASS":  "✁EPASS",
}

SEVERITY_ICON = {
    "CRITICAL": "🔴",
    "HIGH":     "🟠",
    "MEDIUM":   "🟡",
    "LOW":      "🔵",
    "INFO":     "⚪",
}


def format_pr_comment(
    verdict: str,
    semgrep_findings: list,
    claude_severity: str,
    claude_summary: str,
    claude_details: list,
) -> str:
    badge    = VERDICT_BADGE.get(verdict, f"`{verdict}`")
    sev_icon = SEVERITY_ICON.get(claude_severity.upper(), "⚪")

    lines = [
        f"## {badge}  EStackSecAI Policy Gate",
        "",
        "| | |",
        "|---|---|",
        f"| **Claude Severity** | {sev_icon} `{claude_severity}` |",
        f"| **Semgrep Findings** | `{len(semgrep_findings)}` issue(s) |",
        "",
        f"> {claude_summary}",
        "",
    ]

    # Semgrep findings table
    if semgrep_findings:
        lines += [
            "### 🔍 Semgrep Findings",
            "",
            "| Rule | Severity | File | Line |",
            "|------|----------|------|------|",
        ]
        for f in semgrep_findings:
            sev  = f.get("extra", {}).get("severity", " E).upper()
            path = f.get("path", " E)
            line = f.get("start", {}).get("line", " E)
            rule = f.get("check_id", " E).split(".")[-1]
            icon = SEVERITY_ICON.get(sev, "")
            lines.append(f"| `{rule}` | {icon} {sev} | `{path}` | {line} |")
        lines.append("")

    # Claude per-finding details
    if claude_details:
        lines += ["### 🤁EClaude Analysis", ""]
        for d in claude_details:
            lines += [
                f"**`{d.get('rule_id', 'unknown')}`**"
                f"  ELine {d.get('line', '?')}",
                f"- **Risk:** {d.get('message', '')}",
                f"- **Fix:** {d.get('recommendation', '')}",
                "",
            ]

    lines += [
        "---",
        "<sub>Generated by **[StackSecAI](https://rilvak.dev)**"
        " · Policy Gate v0.1</sub>",
    ]
    return "\n".join(lines)

# ── 重褁E��ェチE��用ヘルパ�E ────────────────────────────────────
COMMENT_MARKER = "StackSecAI Policy Gate"


def _find_existing_comment(
    list_url: str,
    headers: dict,
) -> int | None:
    """既存�E StackSecAI コメント�E ID を返す。なければ None、E""
    page = 1
    while True:
        resp = requests.get(
            list_url,
            headers=headers,
            params={"per_page": 100, "page": page},
        )
        resp.raise_for_status()
        comments = resp.json()
        if not comments:
            return None
        for c in comments:
            if COMMENT_MARKER in c.get("body", ""):
                return c["id"]
        if len(comments) < 100:
            return None
        page += 1
# ─────────────────────────────────────────────────────────────

def post_pr_comment(
    verdict: str,
    semgrep_findings: list,
    claude_severity: str,
    claude_summary: str,
    claude_details: list,
) -> None:
    token  = os.environ["GITHUB_TOKEN"]
    repo   = os.environ["GITHUB_REPOSITORY"]
    pr_num = os.environ["PR_NUMBER"]

    body = format_pr_comment(
        verdict, semgrep_findings,
        claude_severity, claude_summary, claude_details,
    )

    list_url = f"https://api.github.com/repos/{repo}/issues/{pr_num}/comments"
    headers = {
        "Authorization": f"Bearer {token}",
        "Accept":        "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }

    existing_id = _find_existing_comment(list_url, headers)

    if existing_id:
        # 既存コメントを更新�E�重褁E��制�E�E        url  = f"https://api.github.com/repos/{repo}/issues/comments/{existing_id}"
        resp = requests.patch(url, json={"body": body}, headers=headers)
    else:
        # 新規投稿
        resp = requests.post(list_url, json={"body": body}, headers=headers)

    resp.raise_for_status()